# Site settings
title: "Italo Izaac | Full Stack Developer"
description: "Italo Izaac, desenvolvedor Full Stack com mais de 10 anos de experiência em desenvolvimento de sistemas."
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Italo Izaac"
user_description: "Desenvolvedor Full Stack, autodidata. Atua há mais de 10 anos com desenvolvimento de sistemas na linguagem PHP. Agora trabalhando principalmente com tecnologias como: <u>Angular</u>, <u>NodeJS</u>, <u>React</u> e <u>React Native</u>. No seu tempo livre, assiste Netflix e fica com sua família, gosta de pesquisar sobre espiritualidade, ufologia e principalmente tecnologias."
user_title: "Full Stack Developer"
email: "italoiz.dev@Gmail.com"
facebook_username: "iiandrade"
linkedin_username: "italoiz"
github_username:  "italoiz"
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
